### ISSUE TITLE
Performance problem with big html and a test js

### ISSUE THREAD

**Issue by Palloxin** [jsfiddle/jsfiddle-users#1894]
![image](https://github.com/user-attachments/assets/68a485a3-ce12-404b-b543-138cdb8d2efa)
Open this fiddle: https://jsfiddle.net/9mtycvdz/
Very long load waiting, lots of ram used (firefox, 4.5 gb peak-chrome 2gb), and somehow infinite website loading (on chrome, after website loaded enough to be fully responsive, the website icon on the tab keeps the loading icon going with CPU use[while it's doing so i cant run the fiddle]).

If you could optimize it..
the JS is a performance tester that loops infinitely for one second. Somehow the big html makes it eat Ram like air, and cpu goes without end for who knows what even after website UI becomes fully responsive.

==
Another thing: excessive use of resources with that javascript code.
-On firefox, When i run that script, it eats A LOT of ram (peak 5gb). It goes from 1gb(normal), => Run code => a very fast increase of ram usage in the fraction of 10 seconds, then goes down somehow quickly to 1gb (edit the "duration" of the loop in the script); the bigger the html, the faster is the increase and bigger the peak ram usage. Is possible to improve resources management on your part?
-On chrome, it loads the fiddle, starts taking an amount of ram 2-3gb depending of html size, and never increase like with firefox. Little detail: the more I run that script the more ram chrome will take from the initial 2-3gb, so 10 runs 3.2gb, 30  runs 3.4gb, 50 runs 3.6gb etc.. I have to reload the fiddle to clean that increase and that's annoying.

**Comment by oskarkrawczyk** [comment]
There's not much to be optimized here. JSFiddle was never meant to be used the way you're trying to use it. It's simply not a benchmarking tool.

CodeMirror (along with its syntax highlighting) has its issues when loading large amounts of code. Our rendered app (what you see in the `iframe`) also won't handle large amounts of post-data too well (it'll timeout and render slowly), because it's not meant to.

The memory and CPU usage is basically not because of how JSFiddle's UI is written it's caused by the code you're trying to add and run.

To be honest, I think you'd be better off using a tool that's specifically written and meant for your use-case.
